### ISSUE TITLE
Add configurable small HTML snippet to the frontend

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#165]
Gitbase needs to provide a user with ability to make small, per-deployment customizations of the frontend.

This feature targets adding non-visual HTML tags, with a main use case of adding common web Analytics snippet to every page, in case a user may want to do so, on one of his own playground deployments.

As a standalone application, gitbase-playground codebase will not include any user tracking, or anything like that.

Simplest way could be adding something like `FOOTER_HTML` ENV VAR configuration option, so that

```sh
$ tee -a ga-snippet.txt << END
<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->
END

$ cat ga-snippet.txt | base64
$ export FOOTER_HTML="PCEtLSBHb29nbGUgQW5hbHl0aWNzIC0tPgo8c2NyaXB0Pgp3aW5kb3cuZ2E9d2luZG93LmdhfHxm
dW5jdGlvbigpeyhnYS5xPWdhLnF8fFtdKS5wdXNoKGFyZ3VtZW50cyl9O2dhLmw9K25ldyBEYXRl
OwpnYSgnY3JlYXRlJywgJ1VBLVhYWFhYLVknLCAnYXV0bycpOwpnYSgnc2VuZCcsICdwYWdldmll
dycpOwo8L3NjcmlwdD4KPHNjcmlwdCBhc3luYyBzcmM9J2h0dHBzOi8vd3d3Lmdvb2dsZS1hbmFs
eXRpY3MuY29tL2FuYWx5dGljcy5qcyc+PC9zY3JpcHQ+CjwhLS0gRW5kIEdvb2dsZSBBbmFseXRp
Y3MgLS0+Cg=="

$ gitbase-playground 
```

adds a snippet to every page.

**Comment by smacker** [comment]
maybe it's better to use file instead of base64 env var?

There is no problem to use files with k8s. Example:
```
kind: ConfigMap
metadata:
  name: my-configs
data:
  some.file.txt: |-
    <content>

kind: Deployment
spec:
  template:
    containers:
      ...
      volumeMounts:
        - name: config-volume
        - mountPath: /etc/my-app/
  volumes:
    - name: config-volume
      configMap: my-configs
```

you can use such pattern in many apps. Few examples from the top of my head:
- [fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch) from kubernetes itself
- [prometheus](https://github.com/kayrus/prometheus-kubernetes) - random example but there are many similar on the internet
