### ISSUE TITLE
Update docker-compose 

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#66]
Update https://github.com/src-d/gitbase-playground/blob/master/docker-compose.yml 

This will help avoiding breaking users i.e on transition of gitbase v0.11.0 -> v0.12.0 

 - fix a particular version of bblfsh image
 - make playground image [depends on](https://docs.docker.com/compose/compose-file/#depends_on) gitbase. Latest version should be fine for both
   ```
   services:
     playground:
       depends_on:
         - gitbase
   ```
 - update [quickstart instructions](https://github.com/src-d/gitbase-playground/blob/master/docs/quickstart.md#run-the-application)
    should include `$ docker-compose pull playground --include-deps`
